empire ={"summary" : ["The Empire, sometimes referred to as the Empire of Man, is an electoral monarchy composed of feudal states that is the largest and most important of the Human nations in the Old World. It was forged by the warrior-king and ascended deity Sigmar from the primitive tribes of Human barbarians who inhabited what became the lands of the southern Empire more than 2500 years ago.",
"Although not as skilled in craftsmanship as the Dwarfs or in magic as the High Elves, the people of the Empire are not beholden by the limits of tradition to the same extent as those elder races and continue to progress culturally, technologically and magically.",
"Having yet to succumb to any threat, external or internal, it is the faith, the sense of righteousness, and the unconquerable spirit of the realm's citizens which gives the Empire its strength, as well as the ruthless efficiency of its military and religious orders.",
"The greatest nation of the Old World, the Empire is ruled by an Emperor and is composed of the descendants of the ancient tribes of Mankind united by the great Human warrior Sigmar Heldenhammer after the Battle of Black Fire Pass. Sigmar was deified after his death by his people and his promise of eternal aid from the Empire for the kingdoms of the Dwarfs still stands today. ",
"This action solidified the relationship between Men and Dwarfs and planted the seeds for the burgeoning Empire through trade between the two races. Today, the Empire is led by Karl Franz I, who rules from his court in the Imperial capital city of Altdorf."],

"electors" : "Averland - Disputed after the death of Marius Leitdorf.\n Hochland - Aldebrand Ludenhof.\nMiddenland - Boris Todbringer.\n Nordland - Theoderic Gausser.\n Ostland - Valmir von Raukov.\n Reikland - Emperor Karl Franz.\n Stirland - Alberich Haupt-Anderssen.\n Talabecland - Helmut Feuerbach.\n Wissenland - Emmanuelle von Liebwitz.\n The Mootland - Hisme Stoutheart.\n Cult of Sigmar - Grand Theogonist Volkmar the Grim, Arch Lectors Kaslain and Aglim.\n Cult of Ulric - Ar-Ulric Emil Valgeir.",

"provinces" : ["The southern Imperial states -- Averland, Reikland, Stirland, Talabecland and Wissenland -- resemble a broad chalice, partially surrounded by near-impassable mountain ranges from which drain the mighty rivers which are the lifeblood of Imperial trade. To the west of these are the Grey Mountains, beyond which lies the Kingdom of Bretonnia and the Wood Elves' magical forest of Athel Loren. To the south are the inhospitable Black Mountains and to the east are the Worlds Edge Mountains that mark the eastern extent of the Old World.",
"To the north, the rolling hills and rapid streams of the south and east are gradually transformed into the forested lowlands and deep waterways that define the heart of the Empire. The vast forests that comprise the central and northern Imperial lands stretch almost unbroken across the countless leagues from the state of Reikland to the northern border with Kislev and the shore of the Sea of Claws.",
"The Great Forest, Drakwald Forest and the Forest of Shadows are all essentially part of the same dark, untamed wilderness, with the green blanket of trees punctured only by the abrupt mountain range known as the Middle Mountains. These lands are divided into the northern Imperial states -- Hochland, Ostermark, Ostland, Middenland and Nordland. The inhabitants of these northern states generally have to deal with much greater hardships and military threats than those of the more civilized south, being that much closer to the daemons, Beastmen and other dangers of the northern Chaos Wastes.",
"Electoral Provinces \n The Electoral Provinces of the Empire include: \n The Grand Principality of Reikland\n The Grand County of Stirland\n The Grand County of Averland\n The Grand Barony of Wissenland\n The Grand Duchy of Talabecland\n The Grand Barony of Hochland\n The League of Ostermark\n The Grand Duchy of Nordland\n The Grand Principality of Ostland\n The Grand Duchy of Middenland\n The Grand County of the Mootland - The Mootland, also called the Moot, is the region of the realm where the Halflings of the Empire dwell, known officially as the Grand County of Mootland. The Moot's elector (currently the Halfling Elder Hisme Stoutheart) is the only non-Human Elector Count in the Empire, and like the Grand Theogonist and Arch Lectors of Sigmar, and the Ar-Ulric, does not wield one of the Runefangs.",
"The former provinces of the Empire and other Imperial regions of note: \n Solland - Solland was destroyed as an independent Imperial province in the wake of Gorbad Ironclaw's Orc invasion of the Empire in 1707 IC and its territory was ultimately absorbed by the Grand Barony of Wissenland. \n  Westerland (The Wasteland) - The Westerland was the Imperial province that was the seat of the great commercial city of Marienburg that seceded from the Empire in 2429 IC and became an independent city-state. Emperor Wilhem III recognized the Westerland's independence after the forces of Marienburg forcefully defeated an Imperial army dispatched to return them to the Imperial fold. The province is now known across the Old World as the Wasteland, perhaps out of a fit of pique on the part of the people of the Empire. \n Sylvania - Sylvania was formerly the County of Sylvania, an independent Imperial province, but it is now officially a fief of the Grand County of Stirland. It can be sure that no other province of the Empire would want the accursed place that was home to the von Carstein line of Vampires and their necromancer and Undead followers. \n Drakwald - Drakwald was a founding Electoral Province of the Empire that was located near the center of the Drakwald Forest, now divided up between Middenland and Nordland."],

"gods" : ["The Patron God \n The Empire has been known to worship a specific God that is not connected with either the Elder or Classical Gods. Instead, the Imperials worships a God who was originally born as a mortal, who founded the Empire and was rewarded by the Old World Pantheons with the ultimate gift of Godhood. \n Sigmar - Warrior-god of Mankind, and the Founder of the Empire.",
"The Northern Gods \n The Elder Gods, also known as the Country Gods or the Northern Gods, are the oldest of the Old World pantheons, whose origins of worship can be traced back for nearly two millennia during the time when primitive Human tribes began to settle within the lands of the Empire and the Old World. \n Taal - God of the Wilds and the husband of Rhya. \n Rhya - Goddess of Agriculture and Birth and the wife of Taal. \n Manann - God of the Sea and the son of Taal and Rhya. \n Ulric - God of Winter and Wolves and the younger brother of Taal.",
"The Southern Gods \n The Classical Gods, also known as the Town Gods or the Southern Gods, are the youngest of the Old World pantheons, whose worship is usually confined to the lands of the southern Empire, and the lands of Tilea and Estalia. \n Morr - God of Death and the husband of Verena. \n Verena - Goddess of Justice and Learning and the wife of Morr. \n Myrmidia - Goddess of Warfare and Strategy and the daughter of Morr and Verena. \n Shallya - Goddess of Mercy and Healing and the daughter of Morr and Verena. \n Ranald - God of Trickery and Thieves. \n Khaine - God of Blood and Murder and the younger brother of Morr."],

"goverment" : ["Contrary to popular beliefs, the Empire is not a unified nation ruled by a powerful central government but is in actuality a massive confederation of fiercely independent states and provinces whose inhabitants are tied together only by a common language, a shared faith in Sigmar and a mutual Imperial culture. Nowadays there are two types of states: the provinces and the city-state. Sigmar was a wise and calculating leader, and he had the foresight to recognize that the Empire was far too big to be ruled by a single man. And so he gave the title of Counts to all the tribal leaders, each responsible for managing his own territory but subject to the Emperor in matters relating to its rulership. Their independence was supposed to counterbalance the power of the Emperor should he proved too tyrannical as a leader, as well as to ensure mutual but non-violent competition amongst each of the Imperial Counts.",
"When it became known that Sigmar did not have an heir to inherit the Imperial Throne, the invention of the electoral system was successful in avoiding a civil war amongst the various Counts, but it however complicated matters even further in creating and maintaining a successive ruler. Those ambitious Elector Counts that wish to become Emperor have been known to give away privileges, titles, and power to any man that will cast his vote for him. The interests of each voters were such that they seldom rallied around a strong candidate, for they may find another of his rivals far more 'generous' in their 'gifts', which has resulted in the weakening of the Imperial system. Even when the Imperial Throne is transferred to his heir by majority vote thanks to the previous Emperor's influence, voters were quick to remind the newly elected Emperor to renew the promises made by his predecessor.",
"While the Empire had a fair share of strong and highly competent Emperors ruling the Empire, many times have the Imperial Throne been occupied by an uncaring Lord who allows his subjects to steal and exploit the Imperial system and her people, often going as far as to ignore the Imperial Edicts once placed by wise and caring rulers of ages past. However, the Imperial System as a whole still continues to work for the Empire as was its purpose, allowing any wise and ambitious Emperor to take the throne and used its powers to better the people under his reign."],

"council" : ["The Council of State \n Due to its size, the Imperial Government is considered far to large and complex for a single man or woman to function properly. It is common that each day, the Emperor must devote attention to dozens of questions, from newly introduced tax policies, the final appeal of a prisoner convicted of treason, or even the official opening of a ceremonial fairground. To succeed in establishing a priority order in this complex system and ensure that only individuals whose cases are really crucial get an audience with the Emperor himself, successive Emperors have often surrounded themselves with advisers chosen from members among the most prominent noble families so that they may assist on legal, financial, diplomatic and military matters in the Emperors stead. Over time, this gathering of councilors turned into a formal meeting, which officially became the Council of State.",
"Members of the State Council: \n Volkmar the Grim - Spiritual Leader.\n Siegfried von Walfen - Chancellor of the Reikland.\n Balthasar Gelt - Counselor of Matters Magical.\n Amadeus Mencken - Chamberlain of the Seal.\n Kurt Helborg - Military Advisor to the Emperor.\n Lotte Hochsvoll - Chancellor of the Imperial Treasury.\n Agatha von Böhrn - Supreme Law Lord.\n Arne Damstadt - Chamberlain of the Imperial House.",
"Each member of the Council controls a large bureaucracy that helps administer the affairs of the state. Such is the importance of their position within the Government that the common people will probably never see these members in person except maybe indirectly in official or ceremonial events."],

"law" : ["Imperial Law \n In theory, the Emperor is free to make whatever laws and regulations he or she wishes and have it apply to the whole of the Empire. The truth is more nuanced, for laws must pass the review of the Prime Estates, who report to the Electors. A bad report is often all the excuse an Elector needs to quietly not enforce the law or deny it altogether, in times of a weak emperor. In such cases, the Emperor, if he is determined to see the law obeyed, will exercise diplomatic and even public pressure on the recalcitrant Elector to come to heel. Often this is enough to gain grudging acceptance. But, if the Elector is determined, an Emperor may claim peremptory jurisdiction and have the case heard in his own courts. In rare cases, continued defiance by an Elector may merit military action, as Karl Franz’s ancestor Wilhelm threatened against Elector Gunnwald of Averland in the case of the Pudding Tax Revolt of 2433.",
"Imperial Law concerns itself mostly with revenues, security from foreign and internal threats, the regulation of sorcery, and the rooting out of Chaos cults. Many Emperors have claimed jurisdiction over the succession to Electoral thrones when the succession is in dispute, and even the right in extreme cases to depose Electors, elevate new families to the Electoral rank, and even give whole provinces to another Elector, as was the case with Drakwald under Emperor Mandred. Though rooted in ancient law and the precedent set by Sigmar himself, no Elector formally acknowledges this right and all resist it in any but the direst cases, lest a lasting precedent is set.",
"Imperial courts exist in all the major cities of the Empire, including the capitals of the Grand Provinces, with judges appointed by the Emperor through the office of the Imperial authority over the case, leading to extended wrangling while the defendant or parties to a civil case swing in the wind."]
}



bretonnia = {"summary" : ["The Kingdom of Bretonnia, also known as the Land of Chivalry, is a highly martial feudal kingdom that lies between the lands of the Grey Mountains and the Great Ocean. Bretonnia is second only in size to that of the Empire, both their chief rival and closest ally, having a culture and society that revolves around the ideals of nobility, social birthright, and the upholding of a strictly enforced code of chivalry.",
"Ruled by a Royarch, the nation of Bretonnia has been known throughout the kingdoms of man for having the greatest Knights in the entire Old World, even surpassing that of the Knightly Orders of the Empire. A proud and honourable kingdom, the armies of Bretonnia are comprised mostly of knights and noblemen, who ride into battle with lance, horse, and sword, seeking glory and rooting out injustice wherever they go. The Knights of Bretonnia are trained to fight from childhood, and even the lowliest Knights Errant are considered superior to ordinary warriors. Their skills are further enhanced through constant training, battles and tournaments. It is not only Bretonnia's knights who are famed, however, for the kingdom also boasts the finest human sailors in the World. With their great sails billowing in the wind, Bretonnia's mighty fleets are a majestic sight on the high seas. Due to this regime, the combined military might of Bretonnia has surpassed that of even the greatest armies in history.",
"The religion that currently dominates this mighty feudal kingdom is the worship of a local elemental deity known only as the Lady of the Lake. This mysterious Goddess of Purity, Light and Order is believed to have aided Gilles le Breton in unifying Bretonnia into a single unified nation, during a Greenskin invasion from the Southern Mountains in 978 IC. The Bretonnian calendar is offset from the Sigmarian Empire's by about 977 years, as the people of the Bretonni weren't fully united until King Gilles' reign as the first Bretonnian monarch.",
"Bretonnia is widely considered to be the fairest and most beautiful land in all the Old World. It is a green land of fertile farms, rolling hills, starkly beautiful mountains, and airy forests. Bretonnian chefs are famous for their culinary skills, and the wine produced in the vineyards of the country is renowned throughout the world. It is seen as a land of honour and virtue, where noble knights keep the domain safe as peasants till the fields, where chivalrous heroes slay monsters and rescue fair damsels. This is the image Bretonnians want to project, and it is not entirely false."],

"goverment" : ["The governmental system that controls much of Bretonnian society is the use and implementation of a feudal system, an outdated archaic political system that was widely used within the Old World many centuries ago, but has seen been removed and replaced with more efficient systems of government. Bretonnia is now the only human kingdom to still follow this system. The functionality of the feudal system is based upon oaths of loyalty between individuals within a society or nation, from which there is little to no direct form of a centralised government. The basic principles of the feudal system is where those below the social ladder must give up their goods and service to those of higher nobility in exchange for protection and certain rights, privileges and titles.",
"The peasantry of Bretonnia form the foundations of this feudal system and are required to serve and obey the nobility without question in exchange for their protection. As such, the vows of the peasants are those of servitude. Above the peasants are the nobles, whose responsibility is the protection of their lands and subjects from the depredations of outside threats, who in exchange for land and a title, shall fight for the King or Royarch when called into war. Thus, the vows of the nobility are ones of fealty.",
"At the very top of this social pyramid is the King or Royarch. The Royarch's rule is sovereign and absolute, with no laws made within the kingdom having any hold upon the actions of the king. The Royarch has the right to do anything he pleases within his realm, and has the ability to create new laws or legislation should he wish it. However, to be a King of Bretonnia requires one to become a Grail Knight, and to be a Grail Knight, one must be the purest of all humanity's hearts.",
"As such, nearly all Kings of Bretonnia are a shining beacon of chivalry, justice, and bravery. The Kings of Bretonnia have been known to truly care for all of his people, constantly finding ways to better the lives of his subjects under his rule and to root out injustice wherever it grows. Thus, the king's power serves as a check on abuses and exploitation made by the lesser nobility.",
"Below the king are the dukes. A Bretonnian duke has royal power within his dukedom, but he is still subject to the king. That means a duke acting within his own dukedom can break the law, unless he disobeys a direct order from the king himself. Unlike royal power, the power of the dukes has been abused, most notably in Mousillon. There is no current duke of Mousillon to avoid having someone hold such authority in such a corrupt area. All dukes hold their land directly from the King. Louen also holds the dukedom of Couronne from the king, and thus holds it from himself. Legally, he is two different people. In theory, the king can create as many dukes as he wants, though the title is meaningless without land. In practice, only the fourteen great fiefs descended from Gilles and his Companions are held to be worthy of this status."],

"religion" : ["The religious spirit of Bretonnia is often as divided as the division between the nobility and peasantry. Within Bretonnian society, the worship of the Lady of the Lake is considered the main religious doctrine. Much of Bretonnian culture is shaped by the actions of the Cult of the Lady, making them a large political power amongst the nobility. However, unlike the worship of other cults, such as the Cult of Sigmar, where Imperial doctrine claims the allegiance of all the Empire's people, the Cult of the Lady is restricted to the nobility. Although the middle class of freemen commoners are allowed to worship at shrines and temples, they are required to pay a tithe unto the brotherhood maintaining such sites. For the nobility, such tithing is entirely voluntary and the amount dependent upon the noble's generosity. Most tithings are thus made for show and to establish their social status and reputation amongst the peerage.",
"The Cult of the Lady is almost entirely restricted to the nobility. Instead, the peasantry often worship the gods of the Old World. The Cult of Ulric has very few followers and even fewer public shrines while the Cult of Myrmidia is growing substantially due to the presence of nearby Estalia. Being a martial god, it is a common theme for peasant soldiers and common militia to revere Myrmidia more than any other deity. The worship of Rhya and Taal is strong amongst farmers, where peasants regularly pray for good weather and a bountiful harvest, to feed their hungry families and to pay the exorbitant tithes and taxes imposed by their lords and masters.",
"The Cult of the Lady \n Revered throughout Bretonnia but almost unknown anywhere else, the Lady of the Lake is the Bretonnian patron goddess of purity, nobility, and courage in the face of danger. She is the romanticised ideal of womanhood, the one fair lady that every knight aspires to love and serve without any doubt or hesitation. Within the minds of many nobles the lady is the very heart and soul of Bretonnia, a mystical elemental incarnation of the land itself and a guardian of all people living within the kingdom. Sacred groves and pools of mystical healing power are her dwelling places, and the magnificent Grail Knights her protectors, devoting themselves to upholding her honour and purity. No base creatures or evildoers can be permitted to profane her sacred sites; this is a duty every knight within Bretonnia, not just Grail Knights, takes very seriously indeed."],

"cities" : ["The Kingdom of Bretonnia is famous for its rural landscape, and lack greatly in the construction of urban environments. However, some of the dukedoms' capitals are cities that were built either as trade-hubs or ports to the sea. Since each duke is also a knight in both duty and status, the capitals of each dukedom are often founded and built upon the remains of ancient Castles that served as the duke's own estate.",
"Castle L'Anguille - Castle L'Anguille is the ducal capital of L'Anguille, famous for its ports and bustling trade.",
"Castle Aquitaine - Castle Aquitiane is the ducal capital of Aquitiane, famous for the Lace Tower, a tall spire built with so many windows that it looks as though it is made from stone lace.",
"Castle Artois - Castle Artois is the ducal capital of Artois, famous for being the only ducal seat with no town outside its heavily fortified walls.",
"Castle Bastonne - Castle Bastonne is the ducal capital of Bastonne, famous for being the original capital of Bretonnia and the seat of power of Gilles le Breton, first Royarch of Bretonnia.",
"Castle Bordeleaux - Castle Bordeleaux is the ducal capital of Bordeleaux, famous for its port and the grand ring of defences that guards the city from sea-born invaders.",
"Castle Brionne - Castle Brionne is the ducal capital of Brionne, famous for its archetypal beauty and a major cultural centre for arts, music, and poetry.",
"Castle Carcassonne - Castle Carcassonne is the ducal capital of Carcassonne, famous for being a large mustering field to gather armies against greenskin invaders.",
"Castle Couronne - Castle Couronne is the ducal capital of Couronne, famous for being the capital and seat of power of Louen Leoncoeur, current Royarch of Bretonnia.",
"Castle Garamont - Castle Garamont is the seat of power for the Castellan of Bastonne, and is thus the main line of defence for the entire dukedom.",
"Castle Gisoreux - Castle Gisoreux is the ducal capital of Gisoreux, famous for being a major trading hub and for having a wide variety of traders and travellers stopping in upon their way along the River Grismerie.", 
"Castle Lyonesse - Castle Lyonesse is the ducal capital of Lyonesse, known for being one of the smallest out of all the ducal capitals.",
"Castle Montfort - Castle Montfort is the ducal capital of Montfort, famous for guarding the western approach of Axe Bite Pass, the main trade route between Bretonnia and the Empire.",
"Castle Mousillon - Castle Mousillon is the ducal capital of Mousillon, famous for being one of the most cursed places within all of Bretonnia.",
"Castle Parravon - Castle Parravon is the ducal capital of Parravon, famous for being carved directly from the rock of the mountain.",
"Castle Quenelles - Castle Quenelles is the ducal capital of Quenelles, famous for being at the very borders of Athel Loren itself.",
"Larret - Larret is a growing community almost as large as a city, famous for its innovation and acceptance of new ideals and technology.",
"Antoch - A mighty fortress-city located on the Gulf of Medes in Araby, Antoch is the greatest of Bretonnia's settlements outside of its own lands.",
"Bregonne - A frontier settlement located on the coast of Lustria, near the island of Tlencan. Bregonne was founded by the renowned knightly explorer, Baron Marcel of Parravon.",
"Turín - A holy city located in Carcassonne, it is famed for containing the Shroud of Gilles le Breton, an artifact of great religious significance."],

"geography" : ["Bretonnia is one of the greatest human realms of the Old World, almost rivalling the Empire in size, wealth, and power. It stretches from the Grey Mountains in the east to the Great Ocean in the west. In the south it is bordered by Estalia and Tilea and to the north its rocky coast is lashed by the stormy Sea of Claws. Unlike the Empire, Bretonnia has a kinder climate and is a more easily cultivated land. Its vast forests and wilderness regions are separated by great fertile plains and valleys where the nobility of Bretonnia have established their feudal domains. It is a rich, strong, chivalrous, and well-defended land.",
"Short-term visitors to Bretonnia see a land of fertile farms, rolling hills, starkly beautiful mountains, and airy forests. The population consists of noble and courteous knights, fair ladies, and contented and deferential peasants.",
"Anyone travelling through Bretonnia, outside the blighted land of Mousillon, sees a country that looks fair and prosperous. The forbidding forests and frowning mountains of the Empire are nowhere to be seen. This does not mean Bretonnia is completely safe, however. Behind the facade, peril lurks. Bretonnia's landscape can be divided into six main types: arable land, where crops are grown; pastoral land, where animals are grazed; forests; mountains; the coast; and the great rivers.",
"The dominant arable crop in Bretonnia is wheat, though oats, barley, and green vegetables are also grown. Fields are very large and divided into strips. Peasant families are responsible for one strip each, and differences in treatment mean many fields look somewhat stripy. Fruit orchards and vineyards are common in the hills, on land that is too steep for easy farming. Sheep are often grazed under fruit trees.",
"It does, however, conceal problems. The mountains are home to Greenskins, the forests to foul creatures. Many peasants are starving, and knights who use courtesy to cloak brutality are found throughout the land. Even the superb flavours of the food often mask rotten ingredients. The cynical say Bretonnia wears a fair mask over deep corruption; the more generous lament the gap often found between its ideals and reality. No one who knows the country at all can ignore the contrast, however."],
}

dwarf = {"summary" : ["The Dwarfs, also called the 'Elder Race,' (or the Dawi as they call themselves) are one of the oldest and proudest intelligent races of the Warhammer World, with a great wealth of history and power that stretches back to time immemorial. They once held an empire which stretched from Norsca in the north to the jungles in the south, and from Mount Silverspear in the east to the Grey Mountains in the west. But the heart of the Dwarfen realm, the Karaz Ankor as they call it, will always lie within the domains of the Worlds Edge Mountains. The highest mountain range in the world, it is filled with the magnificent halls and holds of the Dwarfen people - a testament to the great feats of engineering and power once wielded by this ancient civilization.",
"The Dwarf people as a whole are sturdy and strong, brilliant craftsmen and excellent warriors. Above all they pride themselves on their loyalty to each other or those they are indebted to. This strong bond of kinship has ensured that the Dwarfs stand as one of the most unified races in the world.",
"They are known far and wide as the greatest miners and tunnellers - the ageless halls of Karaz-a-Karak are but one gigantic example of how huge their works can become. The Dwarfs are also highly proficient smiths and craftsmen, capable of producing works far more beautiful than the Elven metalworkers in far Ulthuan and hundreds of times more valuable than the trinkets of Men. Proud, honourable and enduring, it is said that the Dwarfs shall weather the horrors and misery of the world until its final bitter end."],

"goverment" : ["The entire Dwarfen people are all ruled by a spiritual and political leader known as a High King, and below him are a class of lesser Dwarf Kings who each rule a stronghold or Karak (Khazalid for 'mountain stronghold'). In theory, the High King has absolute rule over all of his people and all the Mountain Kingdoms, for he is said to be the direct descendant of an Ancestor God and as such may issue edicts or demands if he so chooses. In reality, however, the High King actually has to consult and cooperate between each of his fellow Kings, and as of tradition and mutual respect, each Dwarf King must follow and answer the edicts imposed by his High King. The current High King of the Dwarfs is Thorgrim Grudgebearer.",
"Each Dwarf King has complete authority within his own Karak and the surrounding territories he occupies. He may pass laws and give edicts to his subjects, but as of tradition, he would usually have a Council of the oldest, wisest and most respected Dwarf to consult the issue and ask for advice. As is the King's duty, a Dwarf King must always put his people and his kingdom's well-being above all others. These duties may range from as simple as hearing the grievances between fellow individuals or clans, to as large as leading a Throng to face the enemy in combat. ",
"The position of a Dwarf King and that of the High King is hereditary, with only those of the original royal-blood line having any legitimacy to control and claim a Karak. As such, a Dwarf King is also the head of the Royal Clan, which are basically extended families who can trace their lineage to the very first Dwarf who had claimed, built, and ruled the Karak from which they are currently living in. Priding themselves in their loyalty between one-another, only a handful of Dwarfs have ever tried to usurp the throne of a Dwarf King in its history, making a large-scale Civil War between various Karaks near non-existent. Only if a royal line is extinguished or disgraced will the throne be open for legitimacy. In such an event, there are several possibilities and outcomes. Either a high-ranking individual such as a Thane or Prince will be found worthy of succession, or a highly prestigious Dwarf Clan can take up the mantle as the new Royal Clan.",
"Below the King is a class of nobles with varying degrees of titles and status, usually taking the name of Thanes. These high-ranking Dwarfs are amongst the oldest, wealthiest, and most skilled individuals within their Kingdom, and each is often the leaders of a single Dwarf Clan. These Thanes owe fealty to their Dwarf King and are allowed to hold an important office within the ruling body, but such a position is not inherently hereditary but rather given to those of great skill and merit."],

"religion" : ["Contrary to popular beliefs, Dwarfs do not worship a certain religion or holy deity, but rather has a belief centred around the veneration and reverence of their ancient ancestors. They believe that the spirits of their ancestors are constantly watching over them, guiding their actions in order to fulfil a grander purpose for the benefit of all Dwarf kind. Dwarf society is often built around these principles, where the oldest amongst their group are often held in higher esteem and respect within the community. Should a very old and highly respected Dwarf die, the community would carve out monumental tombs in order to venerate their deceased ancestors, with the oldest of relics and treasures being both the most highly valued and as a symbol of the ancient power the Dwarfs once wielded",
"It is said in the oldest of Dwarf folklore that there once existed a pantheon of powerful deities who led the Dwarf people into their new-found homes within the Worlds Edge Mountains. Having many names with the Khazalid language, this pantheons is well-known by many outsiders simply as the Ancestor Gods. According to the Dwarfs, these deities were amongst the first of the Dwarfen race, carved by time from the rocks of the mountains, and birthed by the stone itself. Rather than be worshipped in holy reverence like the Gods of the Old World, the Dwarfs consider these ancient deities as living ancestors. In fact, it is said that the High King is the direct descendant of Grungni and Valaya, two of the most important of all the Ancestor Gods. Over the years, these Ancestors eventually gathered a following of like-minded individuals, resulting in the creation of semi-religious Cults, the most prominent of which is the Slayer Cult of Grimnir."],

"society" : ["The most important principles of Dwarf society are often summarised by three things: age, wealth, and skill. The more of these a Dwarf has, the higher you are in Dwarf society. Dwarfs do not boast of their family achievements, they merely set the record straight and proclaim their ancestors' greatness by their own personal wealth and skills. Unlike humans, Dwarfs live naturally long lives, with some growing as old as several centuries to even a thousand years of age. When a Dwarf starts their lives off as young youths, they are often mockingly called by their elders as 'Beardlings'. As their name applies, these youths still have short beards which indicate their young age and will continue to be youths until they reach at least more than 70 years of age. Whilst they age, these youths would learn the basic skills of their Clans, such as mining or smithing. In addition, they would be required to participate for some time in active military duty.",
"The oldest Dwarfs within a community are the 'Longbeards' or 'Greybeards'. Dwarfs never cut or trim their beards, as the length of a beard indicates age, and thus wisdom. As such, these older Dwarfs are highly respected within their communities and their peers, and are often looked to for guidance and leadership. Only a Dwarf who has reached the age of a hundred, or has a beard that is touching the very floor will he be readily considered a Longbeard. Dwarfs also have an affinity for their peoples own past and tradition and would constantly seek to remember their forebears by repairing and maintaining their products. All Dwarfs know how to reforge an ancient blade and are constantly trying to incorporate ancient relics into their newer works. All of the most powerful of these weapons are forged by Gromril, the strongest, rarest, and most treasured metal known to their people."]
}

high_elves = {"summary" : ["The High Elves, or the Asur, as they call themselves, are one of the most ancient and powerful mortal civilisations within the Warhammer World. Hailing from a mighty mist-shrouded island-continent located within the centre of the Great Ocean, the High Elves of Ulthuan are a proud and mighty nation of masterful warriors, peerless mages and lords of the sky and sea. They are an ancient race with powerful armies and even grander magic, building a grand and all-mighty civilisation who, alongside the Dwarfs, fought a long-forgotten, apocalyptic war which saw some of the greatest and most powerful mortal heroes battle against the great darkness that tried to consume the world many thousands of years ago. At the zenith of their power, the world was truly theirs for the taking.",
"Yet their noble and compassionate nature, which was once one of the Elves greatest and most noble character was soon replaced by a great sense of pride and hubris in their own vanity and superiority. In their blind arrogance, they've only succeeded in shattering their once powerful friendship with the Dwarfs, culminating in a Great War which only crippled these two elder races and shattered whatever bright future there was for this young world. Isolated and alone in a world they no longer control, the High Elves are facing the twilight years of their existence, their cities no longer bustling with vibrancy and life as they used to be but now serve as a gloomy reminder of their ultimate, impending demise.",
"The time of the High Elves has passed, or so it is said, yet such is their immense pride that they fight on nonetheless, for they consider themselves the true and rightful protectors of this ancient world, and they believe that so long as their civilisation persist throughout the ages, this dying world will never fall into complete darkness. If oblivion is indeed to be their fate, they have chosen to face it with arrow nocked and sword held high, defending the world they have loved and protected for so long. So do the white-garbed hosts of Ulthuan march to war, banners streaming in the wind and every warrior reconciled to death in service of a greater cause; the protection of this very world. Let the servants of destruction beware their righteous wrath."],

"goverment" : ["Ulthuan is ruled by a collection of princes, princesses and mages, above whom preside the Phoenix King and the Everqueen. The relationship between these rulers is not as simple as the titles would suggest. The kingship is elective while the queenship is hereditary, and both monarchs maintain entirely separate courts. The Everqueen is always the Queen of Avelorn. Her realm is the site of the principal shrine of the Earth Mother, and she is regarded as the spiritual leader of the whole Elven realm. The position of Everqueen is always taken up by the firstborn daughter of the previous queen, conceived during her year-long ritual marriage to the Phoenix King. After this formal marriage, they are free to take new consorts, but only the daughter conceived from the marriage of the Phoenix King and the Everqueen can be the new Everqueen.",
"Hence the Queens of Avelorn have always been the Everqueens of Ulthuan, forming an unbroken chain from ages past. By contrast, the Phoenix King is chosen from among the princes of Ulthuan, one year after the death of the previous incumbent. Each is crowned during a holy ceremony, held at the massive pyramidal Shrine of Asuryan and attended by the legions of the Phoenix Guard and the princes of Ulthuan. The process of choosing the new Phoenix King is rife with intrigue. Emotions often run hot during this fraught and delicate event. Traditionally, the last thirty days of the year of mourning are set aside for the election to take place; however, in practice the debate starts much sooner than that. Often, the politicking starts long before the reigning Phoenix King has died. High Elves love intrigue, and never is the prize greater than when a new Phoenix King is chosen.",
"The grandest of Ulthuan's noble families each look for their candidate to be chosen, and they vie for the support of their peers for their choice. Further to this, each realm in Ulthuan desires the new Phoenix King to be chosen from their land. So it is that rivalries are set aside — or created — to ensure that the agendas of the noble houses are met. For all the deception, manipulation and chicanery employed during the election process, it is almost unheard of for the tactics employed to escalate to violence or outright sabotage. Such actions are considered heretical, for the Phoenix King is the anointed servant of Asuryan. Few High Elf nobles are so consumed with victory that they could believe, even for a moment, that the Creator God would ever approve of a King selected by the ruling council under such dubious and destructive circumstances."],

"religion" : ["The Elven Pantheon are split up into two groups, known as the Cadai and the Cytharai. All Elves revere this pantheon of deities but put a lot more emphasis on certain gods than others. An example of this is the Dark Elves outright ignoring the Cadai Gods and the High Elves shunning the Cytharai Gods. The peaceful, fundamental, and productive aspects of the Elven Pantheon, such as crafting, smiting, motherhood, farming or hunting are represented by the Cadai. The High Elves openly worship and revere the Cadai, building large temples and shrines to profess their faith. Above all other gods is Asuryan, the Creator, who the High Elves worship the most.",
"Then come the rulers of Mirai (the Elven Underworld), whose pantheon are known as the Cytharai. Many Cytharai Gods are shunned by the vast majority of High Elves, yet there are some Cytharai Gods from which the High Elves attempt appeasement. However, even though worshipping the Cytharai Gods in Ulthuan is either frowned upon or totally outlawed depending on the deity in question, some individuals still do privately worship them. For a High Elf to worship Khaine, the Lord of Murder who is the Dark Elves patron God, is to ask to be put to death on the spot. On the other hand the worship of Mathlann, The God of the Deeps is common among elf mariners and is considered in a sense legal for worship.",
"The deities of the High Elves are actually represented by a circular rune pattern call the Pantheonic Mandala. Asuryan being the most important God to the High Elves would be placed in the center, while the others spiral outwards in an order of greatest to least. In secret, some Elves turn to the worship of Slaanesh out of a desire to appease it, so their souls could be spared. Elven worship is greatly desired by Slaanesh, for Elves experience emotions stronger than any other race. This creates the excess for which Slaanesh desires for it gives Slaanesh her power. The worship of Slaanesh and other Chaos Gods is strictly forbidden in Ulthuan, the penalty for doing so is death. To keep Chaos Cults from growing within High Elf society, the Swordmasters of Hoeth work diligently to root out and destroy any cults and cult members found."]
}

lizardmen = {"summary" : ["The Lizardmen, sometimes known as the Cold Ones or the Children of the Gods, are an ancient, savage, intelligent race of cold-blooded, reptilian humanoids that were at one time the first and oldest civilisation of the Warhammer World. Long before the rise of Men, Elf or Dwarf, the empire of the Lizardmen ruled supreme.",
"Alien, enigmatic, and without mercy, the Lizardmen were there when it all began and will be there when the world draws its last dying breath, never tiring nor relenting until order is finally restored to this uncaring, chaotic world. Such is what they were made to do, for they are the ancient servants of the Old Ones, the one true protectors of this very world.",
"Once, in a long and forgotten age, the Lizardmen ruled over it all, dominating this ancient world during an age of primeval monsters. Although their realm is now partly in ruins and overgrown, they seek once more to rise up and reclaim that which they have lost many millennia ago. While the task at hand remains near impossible, the empire of the Lizardmen still fights on -- unleashing their cold-blooded savagery upon any who would stand in the way of their sacred mission.",
"From the lush jungles they come, beneath totems of gold, the Lizardmen march to war, the ground trembling from the approach of their large and mighty reptilian armies. They go to battle for reasons indecipherable to others, an ancient plan known only to themselves.",
"None can ever understand their motives nor their ceaseless drive, for none truly understand that they are the rightful inheritors of the world. It is their sacred, if inscrutable, duty to restore order across the planet. If this means the wholesale eradication of the lesser upstart races outside of the Great Plan, then the Lizardmen empire shall enact this world-spanning genocide once more."],

"hierarhy" : ["The Lizardmen are all ruled by the mystical Slann, the most intelligent and powerful of the Lizardmen. It is they who rule the other Lizardmen as a sacred caste of powerful magic-users, each one bearing the title of Mage-Priests. The Mage-Priest are in all practicality, the political and religious leaders of their entire civilization. All of the Slann living to this very day belong to this sacred caste, because they all possess the ancient intellect and magical powers bred into their race by the Old Ones of a halcyon age.",
"However, all of the Slann that are alive today are only the descendants of those that have seen the Old Ones in person. Those that actually came with the Old Ones are already long dead and their relics lost to time. Within the hierarchy of the Mage-Priest caste, the oldest of the Slann are the most powerful within their caste, each of which are divided into five spawnings in descending order in relations to power and importance.",
"Those of the First Spawning are the greatest and most powerful of them all. Unfortunately, all of them have since died out, leaving the Second Spawning to claim the title of Lord Mage-Priest. There are only five Lords left in existence, but each one reigns over one of the great and major Temple-Cities of the Lizardmen Empire. The Slann of the Third Spawning, known as Master Mage-Priest, are twice as many in numbers and rule the lesser Pyramid-Temples within the Lizardmen realm. The Slann of the Forth Spawning are known as Mage Champions and serve as the generals and leaders of the Lizardmen army in times of war. The Fifth Spawning is the most numerous and are the most energetic and alert of them all. They also occupy the lowest position within their caste and only carry the simple title of Mage-Priest."],

"religion" : ["The Lizardmen all revere the Old Ones as all-mighty deities, the ancient and long forgotten creators of this very world. Many long, bloody millennia have passed since the collapse of the polar gates and the departure of the Old Ones. No living Slann Mage-Priest remains to speak of them and so they passed from memory into legend. Ever since then, the enigmatic Old Ones have come to be regarded not as benevolent rulers of an order spanning the universe and the dimensions, but now as a distant, long-lost pantheon of hungry Gods.",
"With no first hand knowledge of the Old Ones, and with their records scattered and incomplete since the Great Catastrophe, the Lizardmen have but a fragmented picture of their creators. The sacred plaques are replete with oblique and obscure references to various Old Ones and their deeds, and from these the Lizardmen have come to associate specific traits with individual Old Ones. Tlanxa, for example, is an Old One described in many glyphs as the embodiment of the warlike nature of the Lizardmen, and a pair of matching glyphs sequence in Hexoatl and Itza make reference to him riding to war in a all-mighty sky-chariot.",
"Quetli is spoken of in the sacred plaques of Hexoatl as the 'Protector of the True Way'. Xhotl, the Old One after which the temple-city is named, is described in every sequence that mentions him as the chooser of those destined for greatness. As the Lizardmen have come into conflict with more and more races, those Old Ones associated with the martial aspects of the Lizardmen's nature have come to the fore."],

"society" : ["The society of the Lizardmen is highly sophisticated and ancient beyond reckoning. It was they who first became the world's first true civilisations, erecting their cities of ancient stone long before the rise of Men, Elf or Dwarf. It was they who once ruled the world as the most dominant civilisation, eradicating whole species of undesirables from the face of the earth and writing down ancient mathematics and astronomy upon chiseled tablets of stone long before mortals even learned how to write.",
"While many other civilisations have arisen and fallen over the long millennium, it is the Lizardmen who have truly endured throughout all the ages, having been there from the birth of creation unto its final lasting day. Even throughout all this time, Lizardmen society has remained unchanged for millennium, being focused around a highly structured and strictly enforced caste system. This caste system was built and formed by the orders of the Old Ones, whom themselves created each of the separate Lizardmen species to fulfil a certain role in their society.",
"Each and every core species is born into one of these castes. The Lizardmen are taught and perhaps bred to be fanatically loyal to their respective duties, offering little room for any sense of individuality or freedom of thought amongst their kind. Within the system, each caste is composed strictly of one or two of the core species meant to fulfill an extremely important part of Lizardmen society as dictated by the Old Ones instructions, either as workers, warriors or rulers."]
}

skaven = {"summary" : ["The Skaven, sometimes known as the Ratmen, the Ratkin or the Children of the Horned Rat,are a malevolent and diabolical race of large humanoid rat-creatures that inhabit a massive inter-continental underground empire known in their tongue simply as the Under-Empire, where at the very heart of Skavendom lies the horrific city of Skavenblight, the species capital city and the probable birthplace of the Skaven race. The Skaven as a whole are a cruel, treacherous, and highly numerous species that have since spread their loathsome corruption to the farthest corners of the Warhammer World. From deep below the earth, these scavengers have built a vast Empire, whose military power and incomprehensible numbers have the potential to smother the kingdoms of the Old World in a seething tide of violence and anarchy. It is believed by all of Skaven-kind that the world is destined to be theirs, for they consider themselves the Supreme Master Race, undeniably superior in every way to all the other races of the World.",
"This unwavering belief stems from the promises made by their horrifically malevolent deity, known by many legendary names, but his most well-known title is that of the Horned Rat. The Horned Rat is known as the Harbinger of Corruption and Disease, the embodiment of all things the Skaven are or ever will be, and whose worship over the Under-Empire is both supreme and absolute. Within the cruel hierarchy of the Under-Empire, the wishes and demands of the Horned Rat are issued and maintained by the ruthless tyranny of the Council of Thirteen, an organisation that consists of the twelve most powerful Warlords within the Under-Empire whilst the thirteenth seat is reserved for the Horned Rat himself. It is due only to the Council's harsh tyranny that the Under-Empire remained unified in some shape or form for centuries, for none could ever hope to overcome the legions of warriors the Council has under their iron-fisted rule.",
"Out of all the mortal civilisations within the greater world, no single race, neither the ruthless barbarian tribes of the north nor the savage greenskins of the east can be compared in terms of instability to that of the Skaven Under-Empire. The Skaven race as a whole is extremely divided, often far more divided than perhaps any other race known in existence. Such disunion and ruthless lack of cooperation stems from the Skaven's insatiable need to survive, thrive, and reign tyrannically over his brethren. To a Skaven, there is no such thing as pity, remorse, compassion, or cooperation. There is simply survival, survival in a turbulent society that only spares those that possess the brute strength, extreme cunning, and the vicious instinct to outmaneuver and kill the opposition, no matter the cost or the body count of either friend or foe. Though no matter how divided their race may be, they are nonetheless unified in a single cause, and that cause is to conquer the surface world and bring about the Great Ascendancy, where it is said that the Horned Rat's children will swarm across the face of the earth and claim all of it as their own."],

"council" : ["The Council of Thirteen is the ruling body of the Skaven Under-Empire, and whose members are known famously throughout as the Lords of Decay. These Ratlords of the Skaven race oversee all matters pertaining to their entire species, from hatching terrible plots to initiating an invasion against the enemies of their kind. Within the tyrannical hierarchy of the Under-Empire, the Council of Thirteen consists of the warlords of the Four Great Clans as well as seven other lesser warlords.",
"It is considered the right and sovereign duty of the Council of Thirteen to unite the various Greater and Lesser Clans under a single banner. While the Council holds sway over the entirety of the Under-Empire, the reality of a unified Skaven nation has yet to be fully realised. If it were not for the constant squabbling between the various Skaven clans, the Great Ascendancy would have occurred millennia ago. Instead, internecine fighting and bickering hold the Skaven back, much to the benefit of the Old World.",
"Within the capital-city of Skavenblight, the Lords of Decay sit at a long horseshoe table made of pure warpstone and engraved with one of many of the Horned Rats commandments. Seats one through twelve are seated such that the more extreme numbers such as one and twelve are held by the higher ranking members of the council, while the middle seats such as six and seven are held by the lowest ranking members. Seat thirteen is the symbolic seat of the Horned Rat, and it acts as a tie-breaker in votes amongst other members, with the Horned Rats vote typically being interpreted by one of the Grey Seers, often from the Seerlord himself. This effectively gives the Grey Seers an extra vote, as they also hold the first seat.",
"The Council of Thirteen gathers, in whole or in part, at least once a month, and sessions are occasionally called on a weekly basis, especially in times of war. The Council members discuss battle plans, political dilemmas, and important issues that face their race and must vote on what course of action needs to be taken. Politics also plays an important part in the Council’s discussions, and alliances are often made or broken in full view of the other members. The unity of the Council remains, at its core, an illusion. Only when the issue is the direst or when the Horned Rat personally intervenes in the decision-making will the Council ever unite under a single cause."],

"religion" : ["The Horned Rat is the supreme god of the Under-Empire, worshipped by all Skaven and ministered by the Priesthood of the Horned Rat. Though not affiliated with the lords of Chaos, the Horned Rat is certainly a distant relative of those foul, nebulous beings. He represents all things the Skaven are, or wish to be. Undying and eternally scheming, this cunning deity patiently awaits the day of the Great Ascendancy, when his children will swarm across the face of the world, devouring it from within. Entropy is his mantra; decay is his stock in trade. All things must rot, figuratively or literally, and the Horned Rat and his offspring are the worldly reality of this simple truth.",
"All Skaven revere the Horned Rat. None question his existence. Such respect is a product of fear, for the Horned Rat’s eternal hunger does not discriminate between his vermin children and the dwellers of the surface world. A devout Skaven utters small prayers to the Horned God throughout the day, each prayer being a verbal slice of hate, envy, or malice. These prayers are answered often enough to give the Horned Rat validity in the minds of his adherents, even in cases when divine intervention is obviously not involved.",
"Blood sacrifice is common in the day-to-day worship of the Horned Rat. The Skaven fear that if the Horned Rat’s appetite is not satisfied, he will devour his children instead. The form of the sacrifice—a slave, Skaven or otherwise—is not as important as the sacrifice itself. There is no specific doctrine that governs who or what must be sacrificed. The sacrifice itself is enough to sate the Lord of Decay for a brief time. Young victims are considered to be the most potent sacrifices for the Horned Rat, while the blood of the aged and infirm is less desirable."],

"society" : ["Skaven society is often divided between two types of social system, which is separated between a Caste System and a Clan Hierarchy. The Caste System focuses heavily upon the colour of a Skaven fur, which denotes the Skaven as being assigned a particular role in society. Those born with horns and Grey or White fur are considered chosen of the Horned Rat and thus are presented to the Priest or Religious Caste of the Under-Empire. Due to their influential and political power, they are also the most obvious leaders amongst Skaven groups. Those born without horns but have white or grey fur are typically taken to be trained as the Albino Stormvermin Guard of the Council of Thirteen.",
"Below the priestly caste is the militaristic Warrior Caste that are composed almost exclusively of black-furred Skaven. Black fur is considered the mark of a killer and Skaven of that colour are therefore given a position in society that focuses heavily on training these individuals into hardened warriors. In certain cases, a Skaven who does not possess black-fur can still join if he can prove to be just as effective a warrior as any other black-furred Skaven. Such situations, nevertheless, ensure that the Skaven would at least dye their fur black so as to keep to their image as elite warriors.",
"Below the Warrior Caste is the general population of brown-furred Skaven. The Brown-furred Skaven form the very foundations of Skaven society, making them the most diverse in terms of profession, quality of life, and social status. Being outside the Caste System, the brown-furred Skaven are often divided further into certain sects that focus on professions such as trading, building, and the crafting of weapons and goods. All of these groupings allow the Skaven to apply their urge for social climbing on a much larger scale, each sect battling for supremacy over the other, just as each Skaven battles for supremacy within his sect. Outright warfare between these groups is not as common as many would think, simply because the Priest Caste often moderates hostilities between factions by use of terror and cruelty. In their case, the Priest Caste wants to ensure full control over the Under-Empire, and without some form of unity, the Under-Empire as a whole cannot truly exist."]
}

dark_elves = {"summary" : ["The Dark Elves, or the Druchii as they call themselves in their own tongue, also known as the Naggarothi or the 'Dark Ones', are one of the most ancient, powerful, and certainly the most sadistic of the three Elven civilisations of the world. In the bleak, chilly lands of the continent of Naggaroth in the New World lies the Dark Elven kingdoms of the Witch King Malekith, a realm born from the depths of malice and hate, a kingdom that seeks nothing more than to despoil a world its people believe loathes their existence. With malevolent eyes, the Dark Elves watch this dying world, knowing it is their birthright to rule all that they survey and those that live upon it are born to do nothing more than to grovel at their feet.",
"The Druchii are raiders, slavers and heartless reavers of the first degree, their every whim being nothing more than to sow misery and pain to all that oppose them, for misery and pain is the very lifeblood of their existence. Thus do their Black Arks and Corsair Fleets ply the great waters of the world, raiding and enslaving all before them as a tribute to their own avaricious desires.  Yet even should every other land bow to their rule, the Dark Elves know that they cannot claim their glorious inheritance whilst their hated brethren, the High Elves, endure. Until that day finally dawns when the Isles of Ulthuan are finally theirs, the Dark Elves will continue their bloody quest as they always have. Great raiding fleets, their sails black against the night sky, bring woe and destruction to all the shores of the world, bearing terror and death to distant realms, often for no better reason than because there is no one who can stand against them.",
"With every year that passes, the power of Naggaroth ascends to greater heights, built upon the backs of slaves and fuelled by a constant stream of plunder from far-off lands. As the other elder races fade, the Dark Elves thrive, knowing that their hour has at last come. Stormclouds gather across the High Elf realms, and the Witch King's malevolent laughter echoes upon the wind. Naggaroth will rise, Ulthuan will fall, and a vengeance thousands of years in the making will finally see its bloody conclusion."],

"goverment" : ["There is but one ruler of the Dark Elves, and his name is Malekith, the Witch King of Naggaroth. He is the son of Aenarion, greatest of the Elven heroes, and all Elves believe that greatness and destiny lies deep within his very blood and his very soul.",
"None would dare to ever defy the Witch King and his rule, for all those that have no longer live within this world. His rule is absolute, for he is the very embodiment of all the Druchii and so long as he lives, the High Elves will never know true peace.",
"Below the Witch King is a collection of lords and ladies from the major cities of Naggaroth. These lords of the Dark Elves live in six heavily fortified city-states, each one being as powerful and wealthy as any Human kingdom, their innumerable towers built from black stone, rising like sinister pinnacles into the dark storm clouds.",
"All of these cities are evil places, steeped in death and agony. Their lightless dungeons are crammed with captives whose wailings fill the air and whose moans seep through the thick walls of the high towers, saturating the soul with pain and misery. From the tips of the high towers, above the filth and smog of sacrificial fires, the Sorceresses cast their malign magic over the world.",
"Rulership of the Dark Elven kingdoms is rigidly structured, its titles and positions stemming from the ancient traditions of pre-Sundering Nagarythe. New ranks and honours are created only on the rarest occasions, and most of those are abolished at Malekith's decree as soon as he hears of them.",
"For the Witch King to do otherwise would suggest that the royal traditions of Nagarythe were somehow flawed, and if there is one truth closer to Malekith's black heart than any other, it is that the Nagarythe of old was a realm beyond all reproach."],

"religion" : ["The Elves worship a wide variety of deities of varying power and temperament. These beings are divided into two main spheres of influence, with neither having dominance over the other. This is encapsulated in the Elven belief of yenlui, or 'balance' a philosophy that dictates that there must be harmony between the light and dark natures of the Elven spirit.",
"The most widely acknowledged Elven gods outside of Naggaroth are the Cadai, or the gods of the Heavens, who represent the more positive characteristics of Elven culture and the natural world. These are ruled by Asuryan, the greatest of the gods, and include such figures as Isha, goddess of fertility and healing, Kurnous the god of hunters, and Vaul the smith god.",
"In Elven belief many of the unsavoury aspects of their nature and the world at large are also represented by gods known as the Cytharai, or gods of the Underworld. Of these, Khaine is the most well known, being a god of murder and war, but there are others such as Erelth Khial who rules the Underworld, Atharti, a goddess of pleasure and indulgence, and Hekarti the goddess of Dark Magic.",
"These gods are not openly worshipped on Ulthuan by the High Elves, though they have small shrines that are usually shunned except during essential ceremonies for the sole purpose of appeasement. Unlike their cousins on Ulthuan, the Dark Elves openly pay homage to these forbidding powers, the worship of whom rose through the Cults of Excess that preceded the civil war of the Sundering."]
}

demons = {"summary": ["The Daemons of Chaos, known also as the Legions of Chaos, the Arch-Enemy, the Great Beast, or simply just Daemons (not to be confused with other kinds of daemons) are malevolent, otherwordly entities born from the deepest and darkest emotions of all mortal creatures. From their fortresses and palaces within this Realm of Chaos, these entities watch with envious eyes towards the mortal kingdoms, waiting with unblinking patience for their chance to wreak destruction and dismay upon the world and to feed upon the misery that they have wrought.",
"Of the many forces which permeate the world, both emotional and natural otherwise, there are but only Four which holds supreme power within this plane of unnatural existence. Power/Anger, Lust/Pleasure, Death/Despair and Change/Hope are the four greatest forces which have enthralled the world in its grip, for in a world engulfed in such amounts of war, corruption and disease, their dark presence and their malign influence is all but inevitable, for these dark emotions and thoughts fuel the main four Gods of Chaos, Khorne the Blood God, Slaanesh the Dark Prince, Nurgle the Plaguefather and Tzeentch the Changer of Ways.",
"These malevolent entities are the darkness and nightmares of the mortal races given form. They are the product of the misery and pain which engulfs the lands and so long as the evils of mortal races continue its self-destructive nature, from the dark wound within reality that lies at the uppermost north, these entities shall continue to plague the world for all eternity. When the time finally arises, these deamonic entities seize upon the opportunity to break free from their plane of existence, greedily spilling forth to rampage and slaughter in the name of the Chaos Gods.",
"From the Realm of Chaos they come to conquer and destroy, creatures of magic in service to the darkest of gods. Armies flee before them. Devastation lies behind them, for destruction is the gift they bring to warriors of all races, causes and creeds. They are the Daemons of Chaos, the servants of insane and blasphemous gods, and they will not rest until the world shares their madness, until all that is clean, orderly and natural is smothered into the stuff that is raw Chaos."],

"types" : ["Though they are birthed of Chaos, there seems a strange order to the daemonspawn of the Dark Gods. Scholars have identified types of daemons, ranked by relative levels of power, and countless in number. Each seems unique in their awfulness, but they are also alike. There are distinct forms that arise to curse the Old World time and again, each foul type fulfilling a particular role in some unknowable master plan. There is no understanding the reasons for these daemon breeds; there is simply the inscrutable way of Chaos. There are three loose groups of Daemons: Beast, Lesser, and Greater, though even these classifications do not encompass Exalted Daemons, Daemon Princes, or the myriad of the least of all fiends that lurk in the spaces between the realms of Ruinous Powers.",
"Beast Deamons - Beasts are lowly fiends that exist only to serve the wishes and needs of mortal servants. Champions sometimes use them as steeds or as grunts in their armies. Their dim intelligence doesn’t make them any less dangerous, and in some ways it makes them more so, since they have no concerns for their own health and safety. Though it is possible to summon one of these creatures, they are more often sent into the mortal world by the Dark Gods. When bound to the service of a champion or similar owner, they seem to be able to cross the borders between the Chaos Wastes and the Realm of Chaos with impunity, entering and leaving at will.",
"Lesser Daemons - Lesser Daemons have the capacity for thought and reason, and they plot and plan in their ongoing effort to undo mankind’s morality. Though powerful or horrifying, most mortals can deal with them for short periods without compromising their sanity or lives.",
"Greater Daemons - Harbingers of doom, the Greater Daemons are the most powerful servants of the Dark Gods. They are among the mightiest creatures in the entire world, and when they appear, they scorch the very land for miles around with their corruption."],

"incursions" : ["Daemonic invasions are seldom motivated by territory or plunder, for the otherworldly minions of the Dark Gods have no desire for material wealth. Sometimes, incursions are a key element in some divine scheme for supremacy, the lives and deaths of mortals made over into extra pieces upon the Great Game’s sprawling board. But underpinning this truth is that for both the Chaos Gods and the daemons they command, the mortal world is another canvas upon which to paint their own madness. The destruction wrought by a daemon is often not a means to an end, but merely the inevitable by-product of that daemon expressing itself the only way it knows how. Like the Dark Gods they serve, the daemons are generous with their gifts, whether the recipient wishes to receive them or no.",
"Nurgle’s minions spread plague not to bring suffering and despair, but because they are driven to do so by the dark spark of divine essence within them. They cannot conceive of why their diseases should cause such dismay amongst their victims, for a daemon of Nurgle finds nothing more joyous than to be afflicted by pox or pestilence. Daemons of Slaanesh revel in excess, and the torment they bring is — as far as they are concerned — the most philanthropic of blessings. Similarly, Tzeentch’s daemons subvert and mutate the natural order not out of cruelty, but are motivated by a combination of their own easily provoked boredom and the assumption that their victims must similarly be driven to ennui by their static and staid existences — something instantly cured by the mutating gift of change.",
"Only daemons of Khorne are truly selfish, ever seeking to claim skulls for the Skull Throne and so rise to higher status in their dread master’s eyes. In this way, daemons are akin to malicious children who possess a box of fascinating toys that are fragile by nature but unlimited in number. After all, in its own way, the mortal world is as resilient as the Realm of Chaos. A city humbled by plague or broken by war will inevitably recover; a mortal army torn to bloody ruin by fang, blade, and claw or blasted apart by sorcery will soon be replenished or replaced. This may take hundreds of years and cost untold thousands of lives along the way, but daemons don’t reckon time as mortals do, and inevitably find something else to draw their interest in the meantime.",
"Famous Incursions \n The Great Catastrophe - The first and greatest daemonic invasion. \n Great War against Chaos - The second greatest Chaos invasion, during which time the borders of the Chaos realm once extended as far south as the fortress-city of Praag. \n The End Times - The last and perhaps the bloodiest Chaos invasion since the first daemonic invasion."]
}

vampire = {"summary" : ["The Vampire Counts are amongst the most legendary factions of Vampires to have ever terrorised the civilised lands of the Old World, all of whom are members of the unholy Von Carstein bloodline. From the Imperial government and the patriotic citizenry of the Empire, the Vampire Counts are considered by many to be fiends without equal. They seek only to topple the civilisations of the living and supplant them with an Undead Empire that will reign forever as Lords of the Night. The Vampire Counts are powerful necromancers as well as warriors, given supernatural enhancements to their strength, cunning, beauty, and ambition.",
" However, these vampires, for all their power and cunning, are ultimately base, selfish creatures driven by the same motivations as the mortals they deem themselves superior to.[4l] They are remorseless in their advance, killing without thought of mercy or compassion, and whose motives are entirely based on their own selfish desires. For all their refinement, these vampires are nothing but rotting corpses held together by Dark Magic and the horrific consumption of mortal blood.",
"From their powerbase within the former Imperial province of Sylvania, the descendants of the Von Carstein bloodline have tried repeatedly to topple the authority of the Empire. Since the time of Vlad von Carstein, it is the sole purpose of the family to inherit the Empire as their own, using attempts of legitimacy, assassination, and outright invasion to achieve their ambitions. Time and again they have been pushed back towards Sylvania and hunted ceaselessly for their horrific machinations. Yet no matter how many Von Carsteins fall, there always seems to be another willing to take its place, disturbing the graves of the dead and plotting to finally plunge the Empire into their cruel tyranny."],

"hierarchy" : ["The rulership and hierarchy of the Vampire Counts is both simple and brutal in all aspects; only the strongest shall rule. The vampires, and more specifically the von Carsteins, all crave power with an endless hunger, and will stop at nothing to attain the title of Vampire Count. The title of Vampire Count is a prestigious and legendary title that denotes a vampire as the current Vampiric leader of Sylvania and the patriarch of the von Carstein family. Since the creation of the vampire race, there has only been three Vampire Counts in existence. The current reigning Vampire Count is the cunning and deviously powerful Mannfred von Carstein.",
"The title of Vampire Count is usually passed down not by succession, for all vampires are immortal, but by right of strength, being claimed by the strongest amongst the remaining contenders. Once a Vampire Count dies, the remaining vampires usually squabble amongst themselves for the position, leading to a vicious power struggle that could last decades. These events have happened several times in the past, with the most prominent occurring just after the death of the first Vampire Count. Indeed, even when the current Vampire Count still walks the earth, there is always one amongst their numbers who would wish to claim his title by any means necessary."]
}

greenskins = {"summary" : ["The Greenskins are a highly primitive and warlike race of bestial humanoid barbarians and raiders that occupy much of the Eastern Hemisphere of the World. The term 'Greenskins' is a common collective description used by many civilised nations to refer to the forces of the Orcs, Goblins and other biologically related races. The broadest division is between the Orcs, who are strong, brutish, and savage warriors, and the Goblins, who are smaller and weaker, but cunning and conniving creatures.",
"The Greenskins are considered by many to be the scourge of all civilisation. These tribal warriors are extremely violent, raiding ceaselessly, carrying war and barbarism to all corners of the known world. Time and again, hordes of Greenskins would arise without warning and lay a great swath of destruction that has no direction or purpose other than simple violence. Indeed, the Greenskin race's single motive is violence, an ever increasing mass of warfare that has the potential to dominate and cover the entire world in a seething green tide.",
"However, the Greenskins' tendency for warfare has created a division within their society that has ensured their race shall never reach such heights. Since the dawn of their history, the Greenskins have been plagued by a never-ending series of civil wars that has consumed millions of their own kind, for such is their desire for battle that Greenskin tribes have been known to fight each other just as much as they fight the other civilised races of the Old World.",
"Though such strife should spell doom for their race, such are the Greenskins' ability to both survive and thrive in the harshest of environments that they can never truly be exterminated from the face of the world. Without the proper knowledge or unity to progress past even the most basic foundations for a civilisation, the Greenskins never seem to amount to anything more than primitive savages living within scattered tribal societies."],

"hierarchy" : ["Greenskin hierarchy is dominated by the concept of strength. There is no law, and therefore no crime. If a Greenskin feels wronged, he can challenge the source of his grievance to a pit fight. Once the fight is over, the matter is considered settled. Greenskins have no concept of pity; to any Greenskin, the weak are simply weak, and are beneath them in society. A Greenskins can thus attain a higher social rank by simply fighting and defeating members of a higher rank.",
"Because of their bizarre physiology, Orcs would receive a steady supply of adrenaline when preparing to challenge a superior, causing him to physically increase in size and muscle-mass. An alert superior will spot this occurring and promptly beat the challenger down before he becomes a threat. If the superior fails to notice this development, then a battle inevitably results. Should the Orc beat his superiors, he would continue to grow considerably until he would finally challenge the leader of the tribe himself.[4a] In this instance, the leader of a Tribe known as a Warboss is usually always on the alert for potential threats against his tyrannical rule.",
"In most cases, a Warboss would usually assert physical dominance over his underlings on an almost regular basis, which helps to stunt the growth hormones of many potential candidates as well as a way to discourage their rebellious nature. Most of the time, these duties are often handled by the Warboss retinue of Big'Uns, which are Orcs of incredibly massive size and strength whose duty is to keep the rest of the tribe in line.",
"Should an Orc or Goblin manage to have both the size and courage to challenge his Warboss, a duel would then occur. These duels are often extremely one-sided. However, upon the instant that the challenger manages to win the duel, he would instantly become the new leader of a tribe. In the aftermath, the new Warboss would be noticeably larger and stronger than when he first entered, and will continue to grow until he would find an opponent that is even larger and stronger than he is.",
"Goblins on the other hand rarely fight in duels, and would only kill their opponent by more subtle or unconventional means. As such, back-stabbing and subterfuge is the most common form of obtaining a higher social status amongst Goblin dominated tribes, where the value of strength and brutality is usually outweighed by a Goblins sheer cunning and guile."],

"religion" : ["The Gods of the Greenskin are a pairing of powerful War Gods that often embody the baser instincts and emotions that so defines their entire savage race. From the tiniest Goblin to the mightiest Orcish Warlord, all Greenskins would instantly recognize their twin deities simply as Gork and Mork.",
"The Greenskin race venerates these twin Gods, Gork and Mork, for they are the idealised versions of everything they aspire to be: strong, unstoppable, fierce, cunning and lucky. Only the Savage Orcs pays more than lip services to their Gods, as most Orcs are aware that praying to either Gork and Mork is futile, seeing as they don't answer the prayers of cowards, and only those that beg to their Gods are considered cowards by the Greenskins.",
"These two Gods of the Greenskin race embodies that species cunning and brutality. In the Greenskins use of words, Gork is cunningly brutal, while Mork is brutally cunning.[1f] To put it simply, Gork is the embodiment of brutality and close-quarters combat, whilst his twin Mork embodies cunning and the use of unconventional tactics of warfare.",
"As these distinctions can readily be seen between the Orcs and Goblins, it is very common for Orcs to worships Gork's brutality over Mork's cunning, just as much as Goblins prefer Mork's cunning over Gork's brutality. Usually, however, most Greenskins can never understand the difference, and at times consider the twin Gods as one of the same. Nevertheless, these twin Gods of War are always readily worshipped by all Greenskins in almost equal measure.",
"Gork - is the primary deity of clobbering, smashing, breaking, killing and pummelling the rest of the world into submission. This is a notion that resonates strongly with the more warlike and highly volatile Orc sub-species, where their single-mindedness for violence and brutality often out-shadows their otherwise low cunning.",
"Mork - is the patron deity of cunning and shamans. Whereas Gork is most likely to clobber an enemy god in the face, Mork will happily wait until his enemy's back is turned before raising his club and belting him around the back of the head. It is Mork who is revered by the stranger and arguably more intelligent strains of Greenskins, the most prominent of which are the Goblins and Night Goblins."],

"society" : ["Orcs and Goblins live in countless barbaric tribes spread across vast regions within the known world. There are some tribes which include only Goblins or only Orcs, but the majority include both. In these mixed tribes the Orcs will always dominate the smaller and weaker Goblins. Goblin tribes don't have any Orcs at all, as any self-respecting Orc will quickly become the tribe's Boss. The leadership of the tribe almost always belongs to the largest and strongest individual who will impose his rule by any mean necessary. Rivals are defeated in savage fights and most fights are not meant to be fair at all.",
"There is a natural order within Greenskin life that is consistent in almost every tribal society that they occupy. For instance, tribes are often built upon a semi-caste system divided amongst the Orcs and Goblins. The Orc's form the warrior caste of a tribe, providing it with protection, leadership, and warriors, whilst the Goblins form the overall working caste, providing them with something close to craftsmen, builders, herders, and labourers.",
"Contrary to popular beliefs, the Greenskins do possess some forms of agriculture and animal husbandry. These jobs are usually devoted to the Goblins, more particularly the Night Goblins, who have been known to cultivate fungus as food and medicine as well as being the caretakers of the tribes Boars, Wolves, Spiders or most predominately the Squigs.",
"Beyond the natural dominance of the strong over the weak, there is little to no semblance of order within most if not all Greenskin society. Fights and brawls are extremely common, and assassination and death is just a simple part of tribal life. As such, Greenskin societies are extremely unstable, and are prone to strife and constant infighting, even if it is just amongst a small group of individuals."]
}